# Generated by Django 5.0.3 on 2024-03-06 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=15)),
                ('mac_address', models.CharField(max_length=17, unique=True)),
                ('device_type', models.CharField(max_length=100)),
                ('trusted', models.BooleanField(default=False)),
            ],
        ),
    ]
