# Generated by Django 5.0.3 on 2024-03-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_deviceactivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviceactivity',
            name='duration',
        ),
        migrations.AddField(
            model_name='deviceactivity',
            name='is_active',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
