# Generated by Django 5.0.3 on 2024-03-27 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_deviceactivity_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevicePort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.device')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
